### ISSUE TITLE
Crash after I filter the content with checkboxes

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [lapism/SearchBar-SearchView#298]
Hello,

https://stackoverflow.com/questions/40928788/cant-call-void-android-view-view-setelevationfloat-on-null-object-in-lapism-s

I was getting this issue when I was scrolling after do a search with a filter enabled via checkbox.

The solution mentioned in that thread of stackoverflow is working, but maybe you want to fix it.

**Comment by lapism** [comment]
Yes I will fix it in next version.

**Comment by Dahnark** [comment]
@lapism ah, I have to implement flexbox 0.3.0, if I don't implement it SearchView is not working since 5.0.0alpha.

I am using Java 8 too.

**Comment by lapism** [comment]
I know. We found out that too with my colleague. It looks like some kind of bug in Android Studio, we actually do not know right now why it is happening.

**Comment by lapism** [comment]
Also you need CardView probably...

**Comment by Dahnark** [comment]
I was using CardView before add SearchView so I didn't notice.

Maybe is it reported to Google? Really Android Studio has a lot of incomprehensible bugs. The first time that I used 5.0.0alpha I had to clean and rebuild a lot of time, and one of them, Android Studio works and compiled the app... no code changes between each clean or rebuild.

**Comment by lapism** [comment]
Someone should report it :-D. CardView and FlexBox are implemented as dependencies inside this library, but you need to implement both too in main project and this behavior is so strange.  Maybe this is error somewhere in library but I think it is not.

**Comment by Dahnark** [comment]
With version 4.0 I haven't this problem with Flexbox, but I was using Android Studio 2.3 and "compile".

With version 5.0 alpha I directly used Android 3.0 and "implementation".

Maybe there can be the problem?

**Comment by lapism** [comment]
Version 4.0 did not include FlexBox dependency. Honestly I don't know but ,,implementation" is new ,,compile,, which is deprecated now. We will see. This is the reason why I have Alpha versions :D.

**Comment by lapism** [comment]
@Dahnark Hi, please can you add more info? OS version, library version? Is scrolling in AppBar still an issue?

**Comment by Dahnark** [comment]
@lapism API 21-22 (I don't remember if 23 too).

This: `android:stateListAnimator="@null"` solved all.

**Comment by lapism** [comment]
Yes, but I happened in version 4.0. Now it should not happen again. I hope :D

**Comment by lapism** [comment]
Btw. this was happening when SearchView was not in AppBarLayout. It should be fixed already.

**Comment by Dahnark** [comment]
@lapism What should be the place to the SearchView?

coordinatorlayout
    appbarlayout
         collapsingtoolbarlayout

some views

         collapsingtoolbarlayout
    appbarlayout
coordinatorlayout

**SearchView**

**Comment by lapism** [comment]
in coordinatorLayout and use SearchBehavior. More in Readme.

**Comment by Dahnark** [comment]
@lapism I failed, check updated comment

**Comment by lapism** [comment]
Yes. Your Xml should work.

**Comment by Dahnark** [comment]
What does this:  app:layout_behavior="com.lapism.searchview.SearchBehavior"?

I added it I have seen no difference

**Comment by lapism** [comment]
It should scroll like Play Store. But did not try it yet :-D

**Comment by lapism** [comment]
We did not try it yet *

**Comment by Dahnark** [comment]
@lapism mmm do you want to say that searchview should dissapear if toolbar is not visible? In my app it is always visible so I can't check it

**Comment by Dahnark** [comment]
Will be fixed suggestion list with the new alpha? Day after tomorrow I have a trip and I would like to implement add to the beta program a version of my app with this fixed.

Thank you!
