### ISSUE TITLE
java.lang.NoSuchFieldError: No field search_view_shadow 

### ISSUE THREAD

**Issue by kzotin** [lapism/SearchBar-SearchView#328]
Hi,

I'm trying to run super simple example, and App is crashing with following exception:
```
java.lang.NoSuchFieldError: No field search_view_shadow of type I in class Lcom/lapism/searchview/R$id; or its superclasses (declaration of 'com.lapism.searchview.R$id' appears in /data/app/com.agilityscales.app.dev-2/split_lib_slice_2_apk.apk)
                                         at com.lapism.searchview.SearchView.initView(SearchView.java:884)
```

com.lapism.searchview.R is getting generated, but `search_view_shadow` not inside it.

Maybe I'm missing something? Is there any working sample code?

Thanks in advance )

**Comment by kukreja-vikramaditya** [comment]
Facing the same issue.
here is the error log -
http://paste.ubuntu.com/25911280/

gradle -> http://paste.ubuntu.com/25911285/

**Comment by kukreja-vikramaditya** [comment]
Nevermind, I had another search view library.. after removing that this library works fine..Maybe some conflicts could have occurred
