### ISSUE TITLE
Add source code of simple example

### ISSUE THREAD

**Issue by mladenbabic** [lapism/SearchBar-SearchView#352]
Please, add some simple example to test it before we implement it.

**Comment by lapism** [comment]
Again, sorry but no. Library is part of my private project and I do not have time for anything else.

**Comment by EmmanuelMess** [comment]
Why not publish the entire project not just the lib module?

**Comment by lapism** [comment]
For your apps you need only library not my PRIVATE project.

**Comment by EmmanuelMess** [comment]
But it is easier for contributing (your private project shouldn't have more than an app to test and the lib).

**Comment by lapism** [comment]
And it is easy to add this library as a module to your own project ...

**Comment by EmmanuelMess** [comment]
It is easier to have it preadded
