### ISSUE TITLE
Soft keyboard not opening for Kitkat

### ISSUE THREAD

**Issue by Devspm** [lapism/SearchBar-SearchView#358]
Hello,
Thanks for the wonderful library. I'm developing for 4.4 and above, My problem is, the soft keyboard opens except for kitkat when searchview is opened ,any idea ?

**Comment by lapism** [comment]
I did not test it before API 21, so right now I do not know.

**Comment by lapism** [comment]
Did you fix it by yourself? @Devspm

**Comment by Devspm** [comment]
Actually, it works on real device.

**Comment by Devspm** [comment]
But not on the emulator..

**Comment by lapism** [comment]
Ok, I will take a look on it.

**Comment by lapism** [comment]
So I decided to leave everything below API 21. New version is already in JCenter.
