### ISSUE TITLE
How do i get the original index of the suggested item ?

### ISSUE THREAD

**Issue by Devspm** [lapism/SearchBar-SearchView#363]

**Comment by lapism** [comment]
onSearchItemClick(int POSITION, CharSequence title, CharSequence subtitle)

**Comment by Devspm** [comment]
This position changes when query is changed, I needed to get the original index of suggested item, like the index of the item when added to the suggestionList.add(SearchItem);

**Comment by lapism** [comment]
So then get it from your item list.

**Comment by Devspm** [comment]
I needed to get the index of the selected item in the onSearchItem, so far I tried to use the position parameter but it may change, and next I mapped the title param with another list to get the index  but the title is not unique, how do you recommend that I can clear this issue? Thanks for the reply though..
