### ISSUE TITLE
Cannot resolve searchview.

### ISSUE THREAD

**Issue by kozmabalazs** [lapism/SearchBar-SearchView#364]
Hi Martin.

After adding the dependency implementation 'com.lapism:searchview:27.1.0.0.0' to my gradle file, the searchview can not be found.

Only the classes SearchEditText and SearchBehavior are visible.

**Comment by lapism** [comment]
I know about it. You can use it like com.lapism.widget.a OR b. This is temporary solution for a few hours. When I will be back home today I will release fixed version.

**Comment by lapism** [comment]
Weird. I will check it again tomorrow.

**Comment by kozmabalazs** [comment]
I can confirm the issue is still present in release 27.1.0.0.1 .

**Comment by lapism** [comment]
I know. It will be something with ProGuard I think.

**Comment by JavierSegoviaCordoba** [comment]
The last version fixes the problem for me

**Comment by lapism** [comment]
27.1.1.0.0 ?

**Comment by lapism** [comment]
Weird...not for me. I have still this issue with com.lapism.widget.a ...

**Comment by lapism** [comment]
Sorry about that. I did not have time for complete Changelog :(

**Comment by JavierSegoviaCordoba** [comment]
Well, I fixed it in 5 minutes, really not difficult to migrate from the previous version :P

**Comment by JavierSegoviaCordoba** [comment]
@lapism is there any way to use it in API 21-? I know that the Android KitKat and JB have a lot of years but a lot of people still use those versions.

[https://i.imgur.com/Ex3Bixl.png](url)

**Comment by lapism** [comment]
I am glad to hear that :).  Yes, people have them but most of them have newer devices. That was the reason why I moved whole project to API21+.
