### ISSUE TITLE
5 alpha doesn't exist

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [lapism/SearchBar-SearchView#368]
I was checking that you updated to a stable version, this new version uses the same method and structure that 5 alpha?

Should I have to fix something if I update?

I am having the problem too about I can't find searchview, adapter, etc.

**Comment by lapism** [comment]
#364 please read this. I know about this issue.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, I read that yesterday, my question is more about migrating from 5 alpha to the new version.

**Comment by raymondctc** [comment]
Is it possible to keep version 5-alpha or at make a tag on that? Since we have extended some classes and overridden some functions in that version.

**Comment by lapism** [comment]
Please extend new version. It is not difficult. It is going to take about 5 minutes, right @JavierSegoviaCordoba  ? :)
