### ISSUE TITLE
Hamburger to arrow (back button) animation

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [lapism/SearchBar-SearchView#371]
I migrated my app from 5 alpha to the new version, I think it is working perfectly except this animation. How can I force to show back button when searchview is open?

**Comment by lapism** [comment]
There is setLogo with Arrow parameter

**Comment by JavierSegoviaCordoba** [comment]
setLogoHamburgerToLogoArrowWithAnimation(boolean animation);
setLogoHamburgerToLogoArrowWithoutAnimation(boolean animation);

This is not redundant? I think boolean animation is unnecessary or one method should be deleted

**Comment by lapism** [comment]
setAnimationDuration works for both -arrow and whole animation.

**Comment by JavierSegoviaCordoba** [comment]
I can't see the animation with setLogo method too.

I am using it inside onOpen(), I should use it in other place?

**Comment by JavierSegoviaCordoba** [comment]
I think setLogo hasn't animation for me, and setLogoHamburgerToLogoArrowWithAnimation(true); "is working". The problem is the animation is almost finished when the user starts to see the animation.

And is not an animation to use from arrow to hamburger.

**Comment by JavierSegoviaCordoba** [comment]
@Override
            public void onOpen() {
                final Handler handler = new Handler();
                handler.postDelayed(() -> {
                    searchView.setLogoHamburgerToLogoArrowWithAnimation(true);
                }, 400);
            }

General duration in searchView xml is 500. With this, I can see the animation.
