### ISSUE TITLE
Use sensible versioning system

### ISSUE THREAD

**Issue by EmmanuelMess** [lapism/SearchBar-SearchView#377]
I see in [bintray](https://bintray.com/lapism/maven/searchview/view#) that versions were:

3.6.3->3.7->3.8->4.0->27.1.1.0.0

I propose something like 5.1.1 instead of 27.1.1.0.0. BTW why the 27?

**Comment by JavierSegoviaCordoba** [comment]
Versions

The first three numbers are always the same as the latest official Android Support Libraries. The last two numbers are for own updates.

**Comment by EmmanuelMess** [comment]
> The first three numbers are always the same as the latest official Android Support Libraries.

Why would that be?

**Comment by lapism** [comment]
Why you care? I can do what I want to do ...
