### ISSUE TITLE
searchView.close() doesn't close suggestion recyclerview

### ISSUE THREAD

**Issue by 1and1get2** [lapism/SearchBar-SearchView#378]
it seems that if you call `searchView.close()` from within `OnSearchItemClickListener`
(directly or indirectly that is, such as calling `setQuery(title, true)` and call  `searchView.close()`  from within `onQueryTextSubmit`, `SearchView` doesn't call `removeFocus()` or at least not properly

what i mean by that is:

in my implementation
```kotlin
with(searchView){
            theme = R.style.AppTheme
            setOnQueryTextListener(
                    object : Search.OnQueryTextListener {
                        override fun onQueryTextSubmit(query: CharSequence?): Boolean {
                            presenter.onQueryTextSubmit(query.toString())
                            searchView.close()
                            // as a workaround
//                            updateSearchSuggestion(null)
                            return true
                        }

                        override fun onQueryTextChange(newText: CharSequence?) {
                            presenter.onQueryTextChange(newText.toString())
                        }
                    })
            
            searchAdapter.setOnSearchItemClickListener{ position, title, subtitle ->
                Timber.d("setOnSearchItemClickListener $position, $title, $subtitle")
                setQuery(title, true)
                searchView.close()
            }
            searchView.adapter = searchAdapter
        }
```

when clicking on an item in the suggestion list, the list doesn't close/hide, screenshot attached
![screenshot_1525486417](https://user-images.githubusercontent.com/839795/39658791-8c396694-506e-11e8-880f-f1bc4284d99c.png)

however, submitting the query closes the list as expected

**Comment by 1and1get2** [comment]
check out the full code:
[@my github](git@github.com:1and1get2/trademeapidemo.git) at commit f777dc6

**Comment by lapism** [comment]
ASAP

**Comment by lapism** [comment]
This looks like a bug in SearchAdapter. I will take a look on this issue ASAP.

**Comment by lapism** [comment]
You can call something like this  for SearchAdapter and setOnQueryTextListener

    private void getData(CharSequence title) {
        SearchItem item = new SearchItem(this);
        item.setTitle(title);

        mHistoryDatabase.addItem(item);

        mSearchView.close();

        Intent intent = new Intent(BaseActivity.this, SearchActivity.class);
        startActivity(intent);
    }

It works for me.
