### ISSUE TITLE
Flickering when there are no suggestions or history present - searchview:4.0

### ISSUE THREAD

**Issue by poojadeshpande91** [lapism/SearchBar-SearchView#384]
Hi, 

Kindly [check this](https://postimg.cc/image/sldwqolct/) issue. 

As you can see in the GIF image above when there are no suggestions or any history present animation of list is not happening smoothly or when I type any query and clear it I can see flickering/blinks. 

Im currently on `com.lapism:searchview:4.0` version and have implemented as given in samples, how can I fix this?

**Comment by lapism** [comment]
Probably you will have to change to last version here in README. And you will see :+1:

**Comment by poojadeshpande91** [comment]
But latest version requires minSdkVersion version to be 21 while I need 16 in my project, is there any way to fix it in the version I am using ? 

Thank you
